---
name: pull-request-ci
on:
  pull_request_target:
    paths: ['i18n.yaml']

jobs:
  generate-translations:
    defaults:
      run:
        shell: bash

    container:
      image: luzifer/gh-arch-env@sha256:90b9c6e113dfe4d3930474eaf81572f33375277c15536d5028786c1410d7e722
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Re-Generate embedded translations file
        working-directory: ./ci/translate
        run: go run .

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          commit_message: 'CI: Update embedded translations'
          file_pattern: 'src/langs/langs.js'
