---

name: pull-request-ci
on:
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled"]
    branches: ["main"]

permissions:
  contents: write

jobs:
  generate-translations:
    defaults:
      run:
        shell: bash

    container:
      image: luzifer/gh-arch-env
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/ots/ots

      - name: Re-Generate embedded translations file
        working-directory: ./ci/translate
        run: go run .

      - uses: int128/update-generated-files-action@v2
        with:
          commit-message: 'CI: Update embedded translations'

...
